### PR TITLE
Fix accessibility bug on Snackbar button

### PR DESCRIPTION
**Pull request by kldavis4**
There is an issue with the Snackbar when it is configured with an action button where it doesn't take focus and so a screen reader won't announce the alertdialog. This sets autoFocus on the action button and fixes the issue.

*Before* submitting a pull request, please make sure the following is done:

1. Fork the repo and create your branch from `release/MAJOR.MINOR.x`. At the time of creating this, react-md is at version v1.0.0, so you would branch off of `release/1.0.x`.
2. If you have added code that should be tested, please add tests.
3. If you have added new prop types or deprecated prop types, please update the docgen descriptions. When TypeScript is fully implemented, update the types as well.
4. Ensure that the test suite passes (`npm test`).
5. Ensure that your code lints (`npm run lint`).
  > NOTE: Sass changes rely on the Ruby version of `sass` and `scss-lint` to work.
  

6. If your pull request attempts to fix an existing issue, please reference that issue via a commit message or the pull request comment.
7. If this is a new feature or component that has a visual impact, please provide any screenshots or images.

### CODE REVIEW

**Comment by kldavis4** [comment]
thanks :) both of those make sense to me. One other thing is that it feels like there should also always be a dismiss button on the snackbar and that should have the default selection. Otherwise the user will be stuck on the Undo button and have to wait for it to dismiss itself, right?

**Comment by mlaursen** [comment]
Yeah, I think an additional X button or something would be good for those situations but I don't think it should occur for every toast since it is possible just to have text only alerts. This might be something I fix fully in v2 with some of my component API changes/fixes to make it easier to render any element within this snackbar, but have a workaround until then.

**Comment by mlaursen** [comment]
Ok, so I'm thinking that until v2 we can do something like this.

Can you update the `SnackbarContainer` to have a new prop `autoFocusAction` which will default to `true` and pass it down into the `Snackbar` as and apply it to the `btnProps` as `autoFocus` like you have above? This way we can have the `autoFocus` ability and the dev can add custom focus logic as needed when the action is pressed. Then add docgen to `autoFocusAction` to something like:

```
When a toast has an action, it will automatically be focused when this prop is enabled. This will require your action onClick handler to correctly focus an element on the page once the toast is hidden. If this prop is disabled, it is recommended to add custom focus logic so that keyboard users can interact with the snackbar.
```
?

**Comment by kldavis4** [comment]
Sure, I'll give that a shot

**Comment by kldavis4** [comment]
Please see https://github.com/mlaursen/react-md/pull/810 for this.

I still feel like the snackbar needs a way to provide additional actions in order to allow a dismiss button (ex. undo + dismiss). Would like to know if you have thoughts on how to approach that.

**Comment by mlaursen** [comment]
My initial thought is updating the Snackbar and SnackbarContainer components to use the `children` prop as well as adding a children key to each toast so that the Snackbar would look like:

```diff
 const {
   className,
   toast,
   multiline,
   id: propId,
   fab,
   autohide,
   autohideTimeout,
   leaveTimeout,
   onDismiss,
+  children: propChildren,
   ...props
 } = this.props;
-let { text, action } = toast;
+let { text, action, children } = toast;
```

```diff
 <Component
   {...props}
   id={id}
   role={role}
   className={cn('md-snackbar', {
     'md-snackbar--multiline': multiline,
     'md-snackbar--toast': !action,
   }, className)}
 >
   {text}
   {action}
+  {children !== null && (children || propChildren)}
 </Component>
```

This way you can create a "constant" dismiss button in the snackbar by doing something like:

```
<Snackbar {...props}>
  <Button icon onClick={onDismiss}><FontIcon>close</FontIcon></Button>
</Snackbar>
```

or only add the dismiss button as needed by creating a toast like:

```
const toast = {
  text: <span>This is some text.</span>
  children: <Button icon onClick={onDismiss}><FontIcon>close</FontIcon></Button>,
}
```

I haven't tested how the base snackbar styles affects this yet though

**Comment by mlaursen** [comment]
Going to close this one in favor of #810 though

**Pull request closed without merging**
