### PR TITLE
Added componentRef prop to Paper and TabsContainer

### PR DESCRIPTION
**Pull request by gamtiq**
Hello,

I've added `componentRef` prop to `Paper` and `TabsContainer` to have ability to expose DOM refs to parent components.

### CODE REVIEW

**Comment by gamtiq** [comment]
By the way, [node-sass v4.5.3](https://github.com/sass/node-sass/releases/tag/v4.5.3) that is specified as dependency doesn't support Node 9+. As a result it is problematic to setup the project using Node 10. To bypass the problem I've modified `package.json` and have installed the last available node-sass version ([4.12.0](https://github.com/sass/node-sass/releases/tag/v4.12.0) at the moment).

**Comment by mlaursen** [comment]
Would you mind updating this PR so the refs work for Ref Objects as well using `React.createRef()` or `useRef`?

And yeah, I've been meaning to update this branch with a later version of `node-sass` since I normally swap back to node 8 for here. If you'd like to upgrade `node-sass` with this PR, I will accept those changes as well. We can also ignore the Jenkins build error for now as it looks like the `sass` ruby gem reached end of life recently which is causing the failure. It might be fixable by updating the `.travis.yml` to just be `gem install scss_lint` instead of `gem install sass scss_lint`, but I'm not too sure. v2 has switched entirely to `sass-lint` and `node-sass`, so it isn't a problem going forward

**Comment by gamtiq** [comment]
I've added support for ref objects and have updated node-sass version.

**Comment by mlaursen** [comment]
Thanks for the update; looks good to me! I'll release it as v1.11.0 by end of day tomorrow but hopefully some time today

**Comment by gamtiq** [comment]
Thank you!

**Pull request merged**
