### PR TITLE
Enhance Button

### PR DESCRIPTION
**Pull request by gamtiq**
Hello,

I have added:
* [cross-env](https://github.com/kentcdodds/cross-env) to run project's npm scripts in Windows;
* ability to use anything that can be rendered as value for Button's `label` prop;
* `noIcon` prop for Button that allows render children as is.

By the way, on my system the following tests are failed:
```
 FAIL  src\js\TextFields\__tests__\TextArea.js
  ? TextArea > sets the height only for the non-masked text field from the state

    expect(received).toBe(expected)

    Expected value to be (using ===):
      ""
    Received:
      "0px"

      at Object.<anonymous> (src\js\TextFields\__tests__\TextArea.js:152:32)
      at handle (node_modules\worker-farm\lib\child\index.js:41:8)
      at process.<anonymous> (node_modules\worker-farm\lib\child\index.js:47:3)
      at emitTwo (events.js:106:13)
      at process.emit (events.js:191:7)
      at process.nextTick (internal\child_process.js:719:12)
      at _combinedTickCallback (internal\process\next_tick.js:67:7)
      at process._tickCallback (internal\process\next_tick.js:98:9)

  ? TextArea > merges all styles on the non-masked textarea and overrides height

    expect(received).toBe(expected)

    Expected value to be (using ===):
      ""
    Received:
      "0px"

      at Object.<anonymous> (src\js\TextFields\__tests__\TextArea.js:170:32)

 FAIL  src\js\FileInputs\__tests__\FileUpload.js
  ? FileUpload > calls the onChange function still

    TypeError: file argument must be a Blob

      at FileReaderImpl._readFile (node_modules\jsdom\lib\jsdom\living\file-api\FileReader-impl.js:66:13)
      at FileReaderImpl.readAsDataURL (node_modules\jsdom\lib\jsdom\living\file-api\FileReader-impl.js:39:10)
      at FileReader.readAsDataURL (node_modules\jsdom\lib\jsdom\living\generated\FileReader.js:67:35)
      at FileUpload._uploadFile (src\js\FileInputs\FileUpload.js:303:12)
      at src\js\FileInputs\FileUpload.js:340:59
      at Array.forEach (native)
      at FileUpload._handleUpload (src\js\FileInputs\FileUpload.js:339:13)
      at FileInput._handleChange (src\js\FileInputs\FileInput.js:212:9)
      at Object.LinkedValueUtils.executeOnChange (node_modules\react-dom\lib\LinkedValueUtils.js:129:34)
      at ReactDOMComponent._handleChange (node_modules\react-dom\lib\ReactDOMInput.js:232:38)

  ? FileUpload > prevents any files with a size greater than the maxSize

    TypeError: file argument must be a Blob

      at FileReaderImpl._readFile (node_modules\jsdom\lib\jsdom\living\file-api\FileReader-impl.js:66:13)
      at FileReaderImpl.readAsDataURL (node_modules\jsdom\lib\jsdom\living\file-api\FileReader-impl.js:39:10)
      at FileReader.readAsDataURL (node_modules\jsdom\lib\jsdom\living\generated\FileReader.js:67:35)
      at FileUpload._uploadFile (src\js\FileInputs\FileUpload.js:303:12)
      at src\js\FileInputs\FileUpload.js:340:59
      at Array.forEach (native)
      at FileUpload._handleUpload (src\js\FileInputs\FileUpload.js:339:13)
      at FileInput._handleChange (src\js\FileInputs\FileInput.js:212:9)
      at Object.LinkedValueUtils.executeOnChange (node_modules\react-dom\lib\LinkedValueUtils.js:129:34)
      at ReactDOMComponent._handleChange (node_modules\react-dom\lib\ReactDOMInput.js:232:38)
```

And a couple of questions:
1. How to lint project sass files?
1. Are there any plans to use Enzyme for tests?

### CODE REVIEW

**Comment by mlaursen** [comment]
Would you mind merging this into `release/1.1.x` instead of master? You might end up having some merge conflicts.

> How to lint project sass files?

Right now it can only be done with the Ruby Sass and `scss_lint`. I didn't feel like learning the js versions of Sass linting tools and I didn't like the default rules :/

```bash
# I believe it was
$ gem install sass scss_lint
```

> Are there any plans to use Enzyme for tests?

Yeah. I'd really like to add it and some snapshot testing some point. A lot of my tests are pretty old and haven't been updated along with the never versions of Jest/ReactTestUtils. I'd need to learn up a bit more on Enzyme before I could add it myself.

About the tests.. are you using `npm` to install the dependencies or `yarn`? It might be a version difference. I'll check into it!

A somewhat related ticket down the road.. #254

**Comment by gamtiq** [comment]
> Right now it can only be done with the Ruby Sass and scss_lint.

Do you plan migrating to Node-based linter?

> Would you mind merging this into release/1.1.x instead of master?

Ok, I'll do it. I was unsure which branch should be used as a base (`release/1.0.x` or `release/1.1.x`) so I made changes in `master`.

> About the tests.. are you using npm to install the dependencies or yarn?

I use npm.

**Comment by mlaursen** [comment]
> Do you plan migrating to Node-based linter?
I do at some point, it isn't a very high priority to me right now though. It is mostly because the last time I checked into Node-based Sass inters, there wasn't any way to manually disable rules in files like I could with scss-lint.

**Comment by gamtiq** [comment]
I haven't used it but it seems that [sass-lint](https://github.com/sasstools/sass-lint) has ability to disable or enable rules in source files.

**Comment by mlaursen** [comment]
Closed in favor of #261

**Pull request closed without merging**
