### PR TITLE
[ListItem] Optional, right aligned action button with delimiter

### PR DESCRIPTION
**Pull request by Kaishiyoku**
**Screenshots**

chrome_2018-06-21_16-42-32

chrome_2018-06-21_16-42-25

### CODE REVIEW

**Comment by mlaursen** [comment]
Hey! Sorry, I am going to think about this one a bit more before merging. This feels more like something that should be implemented within your code instead of react-md since it isn't part of the material design spec (at least from what I searched). I don't think it'll hurt to add it since there isn't really a nice way to have an additional separate clickable element in a `ListItem` right now, but I'd prefer if it was something I could find within the spec.

This _could_ be solved in a different way by adding a new prop that will allow the `children` to be rendered outside of the `AccessibleFakeButton` so that stuff like this can be created more easily and wouldn't rely on the spec.

Also, [here is a quick example](https://codepen.io/mlaursen03/pen/OEoLXK?editors=0110#) of how you could make this feature with 22 lines of scss + and ~12 lines of JS/React.

Let me think about this some more, but I think I will allow it to be merged since it doesn't hurt anything.

**Comment by Kaishiyoku** [comment]
@mlaursen Your recommendation sounds good - a more generic _children_ approach would be more satisfiable. I could adjust my merge request to this.

**Comment by mlaursen** [comment]
Great! I'm leaning a bit more towards the prop that will allow the `children` to be rendered before, inside, or after the fake button. Would you mind updating the PR for that?

**Comment by Kaishiyoku** [comment]
Of course. Will update the PR next week.

**Comment by Kaishiyoku** [comment]
Ok it seems like there went something wrong with the last travis build. The log says there are lint warnings on lines 567 and 773 at the ListItem.js but that can't be true. How can I rerun the checks other than by pushing a new commit?

**Comment by mlaursen** [comment]
You should be able to just run `npm run lint` for see these errors. But it looks like you might just need to import `Divider` and then add `children` back at line 570 to fix them

**Comment by Kaishiyoku** [comment]
Yes I know @mlaursen - I actually did and when I run `npm run lint` locally everything works just fine; but not on travis.

**Comment by Kaishiyoku** [comment]
@mlaursen pushed the changes

**Comment by mlaursen** [comment]
Great, thanks! I'll update the documentation a bit once it's merged, but I'll target this for 1.5 and try to release by Wednesday

**Pull request merged**
