### PR TITLE
React 16

### PR DESCRIPTION
**Pull request by c0b41**

### CODE REVIEW

**Comment by mlaursen** [comment]
I'm going to wait a little bit before I merge this one. I had tested on the last 16-RC and there were one or two warnings that needed to be fixed. I can also probably update the `Portal` component to hook into the new `ReactDOM.renderPortal` API.

**Comment by c0b41** [comment]
@mlaursen Thanks :+1:

**Comment by laduke** [comment]
```
Warning: Received `false` for non-boolean attribute `focusable`. If this is expected, cast the value to a string.
    in svg (created by SVGIcon)
    in SVGIcon (at layout.js:42)
``` 
is the one I'm seeing.

**Comment by mlaursen** [comment]
So this might actually be a decent change since I'll also need to wait for `react-swipeable-views` and `react-motion` to support react@16 to remove those messages. I'll probably also have to do the migration from `react-transition-group@1.1.2` -> `react-transition-group@2` which is a decent rewrite. I can always do a _half_ solution which patches the `SVGIcon` warning and implement the `Portal` component so it works for react@15 and react@16.

I could just skip some releases and jump to `2.0.0` which drops support below react@16 and does some code cleanup but this kind of ruins my release schedule.. or attempt at a release schedule.

**Comment by noseglid** [comment]
For the record, we've upgraded to `react@16` with `react-md@1.1.x` and haven't seen any issues so far!

**Comment by mlaursen** [comment]
That's good to know! I am planning on doing the "full" react@16 support for the 1.2.0 release. I'm finishing up the Portal testing and the Grid components. Hopefully by the end of next week this will be good to go!

**Comment by mlaursen** [comment]
I am going to close this one if favor of #576. I ended up finding a couple of bugs that had to be fixed while upgrading and I detailed them in that PR.

**Pull request closed without merging**
