### PR TITLE
added aria-hidden to FontIcon <i> element

### PR DESCRIPTION
**Pull request by ma7erick**
The company I work at is requesting that we add a `aria-hidden` attribute to this icon because it is causing accessibility issues with the sorting of the `DataTable` component. The sorting of the table is already being read by the screen reader, but the screen reader is reading the name of the icon as well and we would like to hide it with aria. Please let me know if you have any questions or other ideas about how we could accomplish this.  Thank you!

### CODE REVIEW

**Comment by ma7erick** [comment]
Checks are failing because the aria-hidden attribute is now present in the html and is not matching the tests' snapshots

**Comment by mlaursen** [comment]
I'm a little hesitant to merge this one in since it's a change that is a giant change and affects all users of this library. I think it would be a bit better to define your own `FontIcon` component that is along the lines of:

```jsx
import React from 'react';
import { FontIcon as MDFontIcon } from 'react-md';

const FontIcon = props => <FontIcon aria-hidden {...props} />;

export default FontIcon;
```

You can then import that `FontIcon` instead of the one from `react-md` with the desired behavior:

```jsx
import React from 'react';
import { TableColumn as MDTableColumn } from 'react-md';

import FontIcon from './components/FontIcon'; // or whatever local path should be

const TableColumn = props => <MDTableColumn {...props} sortIcon={<FontIcon>arrow_upward</FontIcon>} />;

export default TableColumn;
```

There are still some use-cases for allowing `FontIcon`s to be read by screen readers (like icon buttons) even though it still is better to use `aria-label` or `aria-labelledby` for that.

**Comment by ma7erick** [comment]
This is a great solution! I will do that. Thanks for your help.

**Comment by mlaursen** [comment]
Glad this worked out :)

**Pull request closed without merging**
