### PR TITLE
[Autocompletes] Add showUnfilteredData flag to show data on focus without value

### LINKED ISSUE #781: [Autocompletes] Allow showing matches on focus with empty value
### Description

This is a suggestion to fit some use cases where we have an autocomplete with only few data.
Having a prop (defaulting to false) to show the matches on focus even with empty data would be helpful in my use-case.

Any though about it? Please feel free to reject to proposition if you think it will not be helpful.

The affected part would be the handle focus function:
```javascript
_handleFocus = (e) => {
   // [...]

   // Adding an extra flag to allow showing data with empty data
   const hasValidValue = !!value || showMatchesWithEmptyData;

   this.setState({
     matchIndex: -1,
     visible: !this.state.manualFocus && hasValidValue && !!this.state.matches.length,
     manualFocus: false,
     focus: true,
   });
 };
```

### Images/Screenshots
N/A

### Link to a gist or code sample where the issue can be reproduced
N/A

### Version
- React - *
- React-MD - ^1.5.0
- Browser - All

### PR DESCRIPTION
**Pull request by Xuecnahc**
Resolves #781

This Pull Request aims to add the `showUnfilteredData` flag to the autocompletes props. It will be used to show the data on focus and change event even if no value is provided to the text box.
Note that the rest of the behavior should stay the same. 

As it is my first Pull Request on the repository please do not hesitate to point out things that I forgot or against the conventions. Please also feel free to reject the Pull Request if you think I am doing it completely wrong.

Also I noticed two things while working on the feature:
- The autocomplete without filter has inconsistent behavior
  - On focus it does not show the data
  - On change with an empty value it shows the data
- There is a trailing space in `docs/src/components/App/Footer/Contribute.jsx`
  - triggers some warning affecting readability

I can fix the second issue in another Pull Request. As for the first one do we want to behavior to be the same as with the `showUnfilteredData` flag? Maybe should we open another issue if we don't plan to do it in this Pull Request.

### CODE REVIEW

**Comment by mlaursen** [comment]
This looks good, thanks! I actually ended up fixing the `docs/src/components/App/Footer/Contribute.jsx` whitespace issue with the 1.5.1 released I just published since I noticed it there.

As for the inconsistencies.. 
My initial thought was that if you set the `filter` prop to `null`, you will have a different service or something else that does the filtering and sorting. So when the input is focused for the first time, your data set should really be an empty list since you haven't typed anything. Once you start typing, the autocomplete data would start populating and be shown. If the user removes all text from the autocomplete, the data result _should_ be empty now and no results should be shown.

If all this logic seems confusing as a user of this library, I think it would be better to make it consistent with the `showUnfilteredData` logic or I can try to update the documentation a bit to help clear up the reasoning for it. What do you think?

**Comment by Xuecnahc** [comment]
My concern is the following:

##### Description

The present data are not shown when present on focus even when the same unfiltered data were shown on change.

##### Setup

- Backend (or mock) returning data on change even for empty value
- Autocomplete without filter

- The documentation [GitHub Ajax Example](https://react-md.mlaursen.com/components/autocompletes#git-hub-ajax-example) is a good example to reproduce the behavior.

##### Step

- Focus the input
  - No data are shown
- Input some text to filter the search
  - Data are shown
- Remove all the text
  - Data are shown
- Blur the input
- Focus the input again
  - No data are shown


The behavior with `onChange` is not the same as with `onFocus` using the same data.
I would be in favor of having the same behavior for both the function.

- Always show present data
- Never show present data for unfiltered data and document the `showUnfilteredData` prop under the filter prop-type.

The second point would be the best in my humble opinion.

Not sure if it makes sense? I may be missing a point in my logic.

**Comment by mlaursen** [comment]
That makes sense. It's actually faulty logic in that example since I don't cancel the api calls when removing characters (deleting all characters at once does what I was hoping). Since my example doesn't even follow the flow, I agree it should be reworked.

I'm a bit unsure of how to resolve the `filter={null}` stuff right now since I'd like to make it backwards compatible as well. Would you be good with me merging this PR and opening another issue to fix the `filter={null}` flows? I agree that the focus and blur behavior should be the same between filterable and unfilterable data.

**Comment by Xuecnahc** [comment]
Thank you a lot for your reply. I opened https://github.com/mlaursen/react-md/issues/791 to resolve the `null` filter issue.

Let me merge this Pull Request.

**Comment by Xuecnahc** [comment]
Hum... Obviously I can not merge it. Please nevermind the second part of my comment.

**Pull request merged**
