### PR TITLE
fix ISSUE 184

### PR DESCRIPTION
**Pull request by daturon**
I hope it will help fix this issue.

### CODE REVIEW

**Comment by CombatCode** [comment]
Just curious, Number.EPSILON can be used there as a corrector?

**Comment by daturon** [comment]
@CombatCode I would not trust such things ;)

**Comment by mlaursen** [comment]
@daturon  would you mind merging this into release/1.0.x instead of master? Otherwise, looks good!

**Comment by daturon** [comment]
@mlaursen oh, sure! I have created a new one.

**Pull request closed without merging**
