### PR TITLE
Typescript: Layover and Drawer types corrections

### LINKED ISSUE #512: TypeScript: DrawerTypes.TEMPORARY
TypeScript definition does not correctly convey that `Drawer.DrawerTypes.TEMPORARY` exists:

```
error TS2339: Property 'TEMPORARY' does not exist on type 'DrawerTypes'.
  Property 'TEMPORARY' does not exist on type '{ FULL_HEIGHT: "full-height"; CLIPPED: "clipped"; FLOATING: "floating"; PERSISTENT: "persistent";...'.
```

### PR DESCRIPTION
**Pull request by noseglid**
I think this is everything needed. It's right in most places. I could only find issues with the LayoverTypes and the DrawerTypes, both of which I've corrected in this PR.

Fixes #512

### CODE REVIEW

**Comment by noseglid** [comment]
Also, I'm uncertain if you want this PR to `master` or `release/1.1.x` ?

**Comment by mlaursen** [comment]
Thanks for the PR! `release/1.1.x` for the future. I normally only update `master` when I have published a patch or a release.

Would you mind also fixing the travis build? Here was the log of the error:
```
> react-md@1.1.1 tsd /home/travis/build/mlaursen/react-md
> cpx "./src/js/**/*.d.ts" ./lib
lib/NavigationDrawers/NavigationDrawer.d.ts(4,3): error TS2305: Module '"/home/travis/build/mlaursen/react-md/lib/Drawers/index"' has no exported member 'DrawerTypes'.
lib/NavigationDrawers/NavigationDrawer.d.ts(5,3): error TS2305: Module '"/home/travis/build/mlaursen/react-md/lib/Drawers/index"' has no exported member 'DrawerTypesType'.
lib/NavigationDrawers/NavigationDrawer.d.ts(6,3): error TS2305: Module '"/home/travis/build/mlaursen/react-md/lib/Drawers/index"' has no exported member 'MobileDrawerTypes'.
lib/NavigationDrawers/NavigationDrawer.d.ts(7,3): error TS2305: Module '"/home/travis/build/mlaursen/react-md/lib/Drawers/index"' has no exported member 'MobileDrawerTypesType'.
lib/NavigationDrawers/NavigationDrawer.d.ts(8,3): error TS2305: Module '"/home/travis/build/mlaursen/react-md/lib/Drawers/index"' has no exported member 'DrawerPositions'.
lib/NavigationDrawers/NavigationDrawer.d.ts(9,3): error TS2305: Module '"/home/travis/build/mlaursen/react-md/lib/Drawers/index"' has no exported member 'MediaTypes'.
index.d.ts(35,42): error TS2305: Module '"/home/travis/build/mlaursen/react-md/lib/Drawers/index"' has no exported member 'MobileDrawerTypes'.
index.d.ts(35,61): error TS2305: Module '"/home/travis/build/mlaursen/react-md/lib/Drawers/index"' has no exported member 'DrawerTypes'.
```

**Comment by noseglid** [comment]
No problem! I'm very happy that you decided to included Typescript typings, and will gladly help you out with any issues we find. We use `react-md` heavily and write all our applications in TypeScript, thus benefit greatly from this.

**Comment by mlaursen** [comment]
Great, thank you! I don't have any applications using this except for my small `with-typescript` example so I don't get all the use cases fully tested with it.

**Pull request merged**
